const GeoLayout og_megaman_wing_cap_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, og_megaman_wing_cap_Wing_Cap_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, og_megaman_wing_cap_Wing_Cap_DL_mesh_layer_4_with_layer_5_revert),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout og_megaman_wing_cap_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
				GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, og_megaman_wing_cap_Wing_Cap_DL_mesh_layer_1_with_layer_1_revert),
						GEO_DISPLAY_LIST(LAYER_ALPHA, og_megaman_wing_cap_Wing_Cap_DL_mesh_layer_4_with_layer_4_revert),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, og_megaman_wing_cap_geo_opt_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
